# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
tone_instructions: |
  프로젝트의 코드 품질 향상과 팀원들의 성장을 목표로 리뷰해주세요.
  1. 심각한 문제와 사소한 문제를 명확히 구분하여 표시.
  2. 피드백은 명확하고 구체적으로 작성하며, 문제의 원인과 개선 방법을 제시.
  3. 리뷰는 교육적이어야 하며, 관련 개념이나 공식 문서 링크를 함께 제공.
  4. 개선 중심의 제안을 우선.
  5. 칭찬은 짧고 위트 있게 작성.
reviews:
  profile: chill
  poem: false
  path_instructions:
    - path: '**/main/**/*.java'
      instructions: |
        1. Java 21 기준으로 리뷰.
        2. 객체지향, 실무 활용 가능성, 불필요한 로직, 클린코드, 리팩토링, 서비스/도메인 설계, 공통 예외 처리를 확인.
        3. 각 리뷰 포인트별로 문제점과 대안, 장단점을 논리적으로 제시하고, 필요한 경우 예시 코드도 추가.
        4. 꼭 필요한 부분에 집중하고, 나머지는 캡션으로 설명.
        5. 리뷰는 해당 라인 범위의 코멘트에 작성.
    - path: '**/test/**/*.java'
      instructions: |
        1. 테스트 네이밍이 명확한지 확인해주세요.
        2. 테스트 코드도 클린코드 관점에서 리뷰해주세요.
        3. 리뷰는 해당 라인 범위의 코멘트에 작성해주세요.
        4. 미작성한 테스트 코드 케이스가 있다면 어떤 테스트가 필요한지 제안해주세요. (80% 기준, 예: API 테스트, Service 단위 테스트, Repository 테스트)
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - 'main'
      - 'develop'
  tools:
    gitleaks:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    semgrep:
      enabled: true
chat:
  auto_reply: true